// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyOBIefau4WDfbEphGWiWzW50zR-FgZdc',
    appId: '1:258986001879:web:b3f078dc6c7578d5377792',
    messagingSenderId: '258986001879',
    projectId: 'lummydb',
    authDomain: 'lummydb.firebaseapp.com',
    storageBucket: 'lummydb.firebasestorage.app',
    measurementId: 'G-LFNNYH6S6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqj05nmbNN3U_jvndfGF1RkrqSfm-2yXE',
    appId: '1:258986001879:android:c76504c105ae0b7e377792',
    messagingSenderId: '258986001879',
    projectId: 'lummydb',
    storageBucket: 'lummydb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlf3GRjmWAKUuMqR2JspyU5BSfM7Y2qSY',
    appId: '1:258986001879:ios:c604aebf789f3a87377792',
    messagingSenderId: '258986001879',
    projectId: 'lummydb',
    storageBucket: 'lummydb.firebasestorage.app',
    iosBundleId: 'com.example.lummy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlf3GRjmWAKUuMqR2JspyU5BSfM7Y2qSY',
    appId: '1:258986001879:ios:c604aebf789f3a87377792',
    messagingSenderId: '258986001879',
    projectId: 'lummydb',
    storageBucket: 'lummydb.firebasestorage.app',
    iosBundleId: 'com.example.lummy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyOBIefau4WDfbEphGWiWzW50zR-FgZdc',
    appId: '1:258986001879:web:cc3eea47fe8a095a377792',
    messagingSenderId: '258986001879',
    projectId: 'lummydb',
    authDomain: 'lummydb.firebaseapp.com',
    storageBucket: 'lummydb.firebasestorage.app',
    measurementId: 'G-C91C7C9VXZ',
  );
}